import { Inter } from "@next/font/google";
import Head from "next/head";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Layout from "./components/Layout";
import Main from "./components/Main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Header />
          <Main
            pageTitle="Home"
            pageDescription="This is the home page of the website."
          />
          <Footer />
        </Layout>
      </main>
    </>
  );
}
